version: '3.9'

services:

  postgres:
    container_name: postgres_md
    restart: unless-stopped
    image: postgres:15.2
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./.db-env
    ports:
      - "7777:5432"
    networks:
      - net

  server:
    build: server/.
    restart: always
    networks:
      - net
    ports:
      - "8761:8761"
    #    volumes:
    #      - /home/nifont/v1/md/tmp/git-props-msm:/app/tmp/git-props-msm
    container_name: server
    image: md/server:1

  client:
    build: client/.
    restart: always
    depends_on:
      - server
    networks:
      - net
    env_file:
      - ./.db-env
      - ./.s3-env
    container_name: client
    image: md/client:1

  gateway:
    build: gateway/.
    restart: always
    depends_on:
      - client
    networks:
      - net
    ports:
      - "8765:8765"
    volumes:
      - ../cert:/etc/ssl/
    container_name: gateway
    image: md/gateway:1

networks:
  net:
    name: md_net