eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  ssl:
    enabled: true
    certificate: classpath:ssl/localhost.cer
    certificate-private-key: classpath:ssl/localhost.pem
    trust-certificate: classpath:ssl/rootca.cer